version: '3'
services:
    jarvis:
        image: "openjarvis/jarvis"
        ports:
            - "80:80"
            - "1883:1883"
            - "2021:2021"
            - "5984:5984"
        volumes:
            - "/jarvis/database:/home/couchdb/data"
            - "/jarvis:/jarvis"
        restart: "always"
        command: "/bin/bash /starter"
        hostname: jarvis
        container_name: jarvis-server-and-web
    updater:
        image: "openjarvis/autoupdate"
        volumes:
            - "/jarvis:/jarvis"
        command: "/bin/bash /starter"
        network_mode: host
        depends_on:
            - jarvis
        hostname: jarvis-updater
        container_name: jarvis-autoupdate
    