version: '3'
services:
    jarvis:
        image: "openjarvis/jarvis:latest"
        ports:
            - "80:80"
            - "1883:1883"
            - "2021:2021"
            - "5984:5984"
        volumes:
            - "/jarvis/logs:/jarvis/logs"
        restart: always
        command: "/bin/bash /starter"
        hostname: jarvis
        container_name: jarvis
